QOL update & delete_inst WIP

diff --git a/qlab b/qlab
--- a/qlab
+++ b/qlab
@@ -1,35 +1,24 @@
 #! /bin/bash
 
 [ "$1" = "-d" ] && set -x
-default=$HOME/snapshots
+default=$HOME/vm/snapshots
+default_instf=$default/.instances
 
-function get_inst {
-if [ -e $default/.instances ] 
-then	
-	printf "$(cat $default/.instances)"
-else
-	printf "No instance file\nExiting...\n" 1>&2
-	exit 1
-fi
-
-}
 
 # get all the snapshot files
-function get_snaps {
 
-exit
-}
-
-
-function start {
-if [ -e $default/.instances -a -s $default/.instances ]
+function start_tmp {
+if [ -e $default_instf -a -s $default_instf ]
 then
 	printf "Choose one of the following instances: \n"
-	awk -F "@@@" '{ if ( $3 == "none" ) print "\n" NR ")\nName: "$1"\nCommand: "$2" -drive file="$4; else print "\n" NR ")\nName: "$1"\nCommand: "$2" -drive file="$4","$3 }' $default/.instances
+	awk -F "@@@" '{ if ( $3 == "none" ) print "\n" NR ")\nName: "$1"\nCommand: "$2" -drive file="$4; else print "\n" NR ")\nName: "$1"\nCommand: "$2" -drive file="$4","$3 }' $default_instf
 	printf "> "; read instance
 	if [[ $instance =~ ^[0-9]+$ ]]
 	then
-		eval $(awk -F "@@@" 'NR == '$instance' { if ( $3 == "none" ) print $2" -drive file="$4; else print $2" -drive file="$4","$3 }' $default/.instances)
+		eval $(awk -F "@@@" 'NR == '$instance' { if ( $3 == "none" ) print $2" -drive file="$4; else print $2" -drive file="$4","$3 }' $default_instf)
+	elif [ "$instance" = "e" -o "$instance" = "exit" ]
+	then
+		printf "Returning to main menu\n"
 	else
 		printf "Number was not inputed\nRestarting...\n"
 		start
@@ -40,11 +29,23 @@ else
 fi
 }
 
-function write {
-[ -e $default/.instances ] || printf "" > $default/.instances
+function list_inst {
+if [ -e $default_instf ] 
+then	
+	printf "\nList of instances:\n\n"
+	awk -F "@@@" '{ if ( $3 == "none" ) print "\n" NR ")\nName: "$1"\nCommand: "$2" -drive file="$4; else print "\n" NR ")\nName: "$1"\nCommand: "$2" -drive file="$4","$3 }' $default_instf
+else
+	printf "No instance file\nExiting...\n" 1>&2
+	exit 1
+fi
+
+}
+
+function write_inst {
+[ -e $default_instf ] || printf "" > $default_instf
 if [ $? != 0 ]
 then
-	printf "Unable to create instances file $default/.instances\nExiting...\n"
+	printf "Unable to create instances file $default_instf\nExiting...\n"
 	exit 1
 fi
 
@@ -56,29 +57,46 @@ printf "Full path of the OS drive (specified with -drive file=<path>)\n> "
 read drive_path
 printf "Any other drive options (ex: if=<interface>, bus=<bus>)[default: \"\"] "
 read ext
-
-if [ -n "$name" -a -n "$com" -a -n "$drive_path" ] && awk -F "@@@" '$1 ~ /'$name'/ { exit 1 }' $default/.instances
+if [ "$name" = "exit" -o "$name" = "e" -o "$com" = "exit" -o "$com" = "e" -o "$drive_path" = "exit" -o "$drive_path" = "e" -o "$ext" = "exit" -o "$ext" = "e" ]
+then
+	printf "Returning to main menu\n"
+elif [ -n "$name" -a -n "$com" -a -n "$drive_path" ] && awk -F "@@@" '$1 ~ /'$name'/ { exit 1 }' $default_instf
 then
 	printf "Is this your final command: $com -drive file=$drive_path,$ext(y/n) "
 	read ans
 	[ -z $ext ] && ext="none"
-	[ "$ans" = "y" ] && printf "$name@@@$com@@@$ext@@@${drive_path}\n" >> $default/.instances || write
+	[ "$ans" = "y" ] && printf "$name@@@$com@@@$ext@@@${drive_path}\n" >> $default_instf || write
 else
 	printf "A parameter was left blank or the your name is the same as a previously named instance...\nRestarting\n"
-	write
+	write_inst
 fi
 
 
 }
 
-function create {
+function delete_inst {
+[ -e $default_instf -a -s $default_instf ] || (printf "$default_instf not found or is empty\nExiting...\n" ; exit 1)
+list_inst
+printf "Which instance would you like to delete: "
+read del
+
+if [ "$del" -le "$(wc -l $default_instf | awk '{ print $1 }')" -a "$del" -ge "1" ]
+then
+	awk 'NR != '$del' { print }
+fi
+
+}
+
+function create_snap {
 
 exit
 }
-function delete {
+
+function delete_snap {
 
 exit
 }
+
 
 
 function main {
@@ -89,35 +107,42 @@ function main {
 		exit 1
 	fi
 
-	printf "1) Start an instance as a snapshot (temporary)\n\
-2) Write a new instance\n\
-2) Create a Snapshot file for an instance\n\
-3) Delete a Snapshot file for an instance\n\
+	printf "\n1) Start an instance as a snapshot (temporary)\n\
+2) List instances\n\
+3) Write a new instance\n\
+4) Delete a an instance\n\
+5) Create a Snapshot file for an instance\n\
+6) Delete a Snapshot file for an instance\n\
 > "
 	read opt
 	case $opt in
 		1)
-			start
+			start_tmp
 			;;
 		2)
-			write
+			list_inst
 			;;
 		3)
-			create
+			write_inst
 			;;
 		4)
-			delete
+			delete_inst
+			;;
+		5)
+			create_snap
+			;;
+		6)
+			delete_snap
 			;;
 		*)
-			printf "Option not found\nExiting...\n"
-			exit 1
+			printf "Option not found\n"
 			;;
 	esac
 
 
 }
 
-printf "QLab - QEMU Snapshot manager\n\n"
+printf "QLab - QEMU Snapshot manager\n"
 if qemu-img --version > /dev/null 2>&1
 then
 	while :
